# Generated by Django 4.0 on 2022-01-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Гпуппы',
            },
        ),
        migrations.CreateModel(
            name='GroupArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_in_article', to='articles.article')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='articles.group')),
            ],
            options={
                'db_table': 'articles_group_article',
                'ordering': ['-is_main', 'groups__title'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='groups',
            field=models.ManyToManyField(through='articles.GroupArticle', to='articles.Group'),
        ),
    ]
