# Generated by Django 4.0 on 2022-01-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_group_grouparticle_article_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouparticle',
            options={'ordering': ['-is_main', 'tag__name']},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='grouparticle',
            old_name='groups',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scopes', to='articles.article'),
        ),
    ]
